### ISSUE TITLE
Chapter 02의 Interface/Concrete class naming

### ISSUE THREAD

**Issue by crowjdh** [Yooii-Studios/Clean-Code#1]
public class ViewCompat {
    interface ViewCompatImpl {
        public boolean canScrollHorizontally(View v, int direction);
        public boolean canScrollVertically(View v, int direction);
        public int getOverScrollMode(View v);
        public void setOverScrollMode(View v, int mode);
        ...
    }

    static final ViewCompatImpl IMPL;
    static {
        final int version = android.os.Build.VERSION.SDK_INT;
        if (version >= 21) {
            IMPL = new Api21ViewCompatImpl();
        } else if (version >= 19) {
            IMPL = new KitKatViewCompatImpl();
        } else if (version >= 17) {
            IMPL = new JbMr1ViewCompatImpl();
        } else if (version >= 16) {
            IMPL = new JBViewCompatImpl();
        } else if (version >= 14) {
            IMPL = new ICSViewCompatImpl();
        } else if (version >= 11) {
            IMPL = new HCViewCompatImpl();
        } else if (version >= 9) {
            IMPL = new GBViewCompatImpl();
        } else if (version >= 7) {
            IMPL = new EclairMr1ViewCompatImpl();
        } else {
            IMPL = new BaseViewCompatImpl();
        }
    }

    static class BaseViewCompatImpl implements ViewCompatImpl {
        ...
    }

    static class EclairMr1ViewCompatImpl extends BaseViewCompatImpl {
        ...
    }

    ...
    // 메소드 구현부
    /**
     * Check if this view can be scrolled horizontally in a certain direction.
     *
     * @param v The View against which to invoke the method.
     * @param direction Negative to check scrolling left, positive to check scrolling right.
     * @return true if this view can be scrolled in the specified direction, false otherwise.
     */
    public static boolean canScrollHorizontally(View v, int direction) {
        return IMPL.canScrollHorizontally(v, direction);
    }

    /**
     * Check if this view can be scrolled vertically in a certain direction.
     *
     * @param v The View against which to invoke the method.
     * @param direction Negative to check scrolling up, positive to check scrolling down.
     * @return true if this view can be scrolled in the specified direction, false otherwise.
     */
    public static boolean canScrollVertically(View v, int direction) {
        return IMPL.canScrollVertically(v, direction);
    }
}

//

위와 같이 인터페이스와 구현 클래스 모두에 Impl을 붙이고 있음.
같이 토의해보면 좋을듯.

**Comment by crowjdh** [comment]
원칙에 따라 Impl은 구현체에만 붙이는 방향이 좋을것 같습니다.
구글에서 작성한 소스코드이기 때문에 완전히 무시할 수는 없겠지만 구글의 "자바 스타일 가이드"에서도 이 이슈에 해당하는 항목을 찾을 수 없기 때문에 기본적으로 원칙대로 처리하는게 맞을것 같네요.

한편으로는 그저 "큰 덩치의 프레임워크"를 만들다 보니 발생한 실수일지도 모르겠다는 생각도 듭니다.

참조
- Google Java Style: https://google.github.io/styleguide/javaguide.html

**Comment by kwosu87** [comment]
얘기 결과 자바 스타일의 경우 interface에는 IMyClass, 구현부는 MyClass와 같은 식을 사용하거나, MyClass + MyClassImpl 의 조합으로 사용하고 있는데, 후자를 사용하는 것이 좋겠다고 1차적인 결론을 내림. 

Chatper 2의 내용을 봐도 I를 붙이는 방식은 Don't 이라고 하지 마라고 하고 있기 때문이기도 함.
