### ISSUE TITLE
Chapter 09 - 단위 테스트.md 오타

### ISSUE THREAD

**Issue by soldier4443** [Yooii-Studios/Clean-Code#17]
[테스트 당 assert 하나](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2009%20-%20%EB%8B%A8%EC%9C%84%20%ED%85%8C%EC%8A%A4%ED%8A%B8.md#%ED%85%8C%EC%8A%A4%ED%8A%B8-%EB%8B%B9-assert-%ED%95%98%EB%82%98) 절에

give-when-them이 아니라 give-when-then으로 수정해야할 것 같습니다

**Comment by crowjdh** [comment]
리포트 감사합니다. c84b3f3ad42408da862792c14091760fbd73cc05 커밋에서 수정됐습니다.😄

**Comment by innocarpe** [comment]
리포트 감사합니당. 😃
