### ISSUE TITLE
gitbook이 md로 바로 링크하는 용도인가요?

### ISSUE THREAD

**Issue by wdh2100** [Yooii-Studios/Clean-Code#19]
안녕하세요?

정리 잘되어있네요.

잘 읽고 있습니다.

https://kwosu87.gitbooks.io/clean-code/content/

목차에 있는걸 누르면 gitbook에서 바로 보는게 아니라 해당 md파일로 링크연결하는 용도인가요?

**Comment by innocarpe** [comment]
안녕하세요 @wdh2100 님, 평소에 잘 들어오지 않는 레포다 보니 너무 늦게 발견했네요.

gitbook 페이지는 이 레포의 리플렉션이라 볼 수 있는 개념이라 그걸 의도한 것이 맞기는 해요. 이 레포의 README 에서 해당 페이지로 바로 이동하도록 한 것이 의도였습니다.

다만 gitbook 페이지 자체가 제대로 동작하지 않는 것 같아서 새로 gitbook 을 만들고 링크를 수정하도록 README 를 고쳤습니다. #20 을 참고해 주셔요!

**Comment by crowjdh** [comment]
#20 으로 문제 해결돼서 닫습니다.
