### ISSUE TITLE
한국 개발자에게 주석이란 어떤 의미일까?

### ISSUE THREAD

**Issue by sookim4u** [Yooii-Studios/Clean-Code#21]
S/W 대가가 주석 챕터에서 언급하지 않은 부분이 있다.
그것은 외국인 프로그래머의 경우는 어찌 할 것인가? 
나는 전산과 84학번으로 지금도 현업에서 프로그램을 개발한다.
내가 만나본 대부분의 개발자들은 영어를 잘 못한다. 영어문장으로 된 아래의 경우에서,
한국어로 주석을 달아 놓으면 직관적으로 이해가 쉽다.
책에 주석으로 한국인이 주석을 어찌 대해야 할지 추가해 놓지 않은 점이 아쉽다.
/**
 * @class Existence : 존재에 대하여
 *
 *        데카르트
 *        Cogito, ergo sum (라틴어)
 *        나는 생각한다. 그러므로 나는 존재한다.
 *        I think,therefore I am
 */
public class Existence {

    // 1. 보통의 미국인 프로그래머
    // I think, therefore I am --> 동어반복, 무의미한 주석
    void iThinkThereforeIam() {
    }

    /**
     * 2. 라틴어를 좋아하는 미국인 프로그래머
     */
    // I think, therefore I am --> 외국어 이름이어서 유의미한 주석, 그러나 라틴어 매소드 이름은 영어로 바꾸어야 하겠다.
    void cogitoErgoSum() {
    }

    /**
     * 3. 보통의 한국인 프로그래머
     */
    // 나는 생각한다. 그러므로 나는 존재한다. --> 외국어 매소드 이름이어서 유의미한 주석
    void iThinkThereforeIam() {
    }
}

**Comment by crowjdh** [comment]
@sookim4u  의견 감사합니다.

내용이 이슈라기 보다는 의논에 가까운 것 같아서 코드 하이라이팅 후 Discusstions(상단탭 `Code - Issues - Pull requests - [Discussions]`)탭 내 Ideas 카테고리로 이전했습니다.
위 내용 확인하시고 이 이슈는 직접 닫아주시면 감사하겠습니다.

**Comment by sookim4u** [comment]
Discusstions(상단탭 Code - Issues - Pull requests - [Discussions])탭 내 Ideas 카테고리로 이전
