### ISSUE TITLE
<!-- Raised an issue to propose your change (https://github.com/cvat-ai/cvat/issues).

### ISSUE THREAD

**Issue by Gitgody** [Yooii-Studios/Clean-Code#25]
### Motivation and context

This PR simplifies usage of SDK/CLI in simple cases, when CVAT is deployed with default parameters. Now, we don't need to specify schema or port in these cases.

- Added schema autodetection in SDK
- SDK uses default http (80) and https (443) ports for connections
- Removed the `--https` CLI arg

### How has this been tested?

Unit tests

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
  

_Publicación original de @zhiltsov-max en https://github.com/opencv/cvat/pull/4910_

**Comment by crowjdh** [comment]
@Gitgody This is your third time spamming unrelated issue. This is not your notepad, and people are watching, so please take responsibility and don't post unrelated issue.
