### ISSUE TITLE
함수에서 return이 하나여야만 하는 이유가 궁금합니다.

### ISSUE THREAD

**Issue by devxoul** [Yooii-Studios/Clean-Code#7]
안녕하세요.

'Chapter 3 - 함수' 챕터의 [구조적 프로그래밍](https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2003%20-%20%ED%95%A8%EC%88%98.md#구조적-프로그래밍) 섹션에서는 함수의 return이 하나인 코드가 읽기 쉽고 이해하기 쉬운 코드라고 하셨는데요.

> 즉, 함수는 return문이 하나여야 되며, 루프 안에서 break나 continue를 사용해선 안된다고 한다.

일반적으로 선호되는 방식과는 조금 다른 것 같아 질문드립니다.

코드 복잡도를 줄이고, 읽기 쉬운 코드를 작성하는 다양한 방법 중 하나로 거론되는 것이 바로 **반대의 경우에 대해 일찍 반환**하도록 하는 것입니다. Mozilla의 [Coding style](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#Return_from_errors_immediately)에서도 권고하는 방식이고, 구글에서 'early return vs nested if' 키워드로 검색해도 대부분 early return을 선호하는 것을 알 수 있습니다.

혹시, return을 여러번 사용하는 대신 한 번을 사용하게 되면서 코드가 간결해지는 예시를 들어주실 수 있으신가요? 혹은 함수에서 return을 사용하는 곳이 많은 경우 코드가 간결해지지 않는 예시가 있다면 이해하는데 도움이 될 듯 합니다.

만약 제가 잘못 이해한 것이라면 지적해주시면 감사하겠습니다.
감사합니다.

**Comment by webhacking** [comment]
코드의 복잡도를 줄인다면 return이 하나여야만한다는것도 틀린말은 아니것같습니다만....

**Comment by kwosu87** [comment]
책을 다시 살펴봤는데, 내용이 조금 누락이 되어 있어서 오해를 살 부분이 있을 것 같습니다. 수정을 해 두어야 할 것 같은데 책을 보고 말씀을 드리자면, 

다익스크라의 구조적 프로그래밍 원칙에 따르면 모든 함수와 함수 내 모든 블록에 입구와 출구가 하나만 존재해야 한다고 말하는데요, 대부분의 경우 유용할 수 있고 특히 **루프 안에서 break나 continue를 사용해서 안 되며 goto는 절대로, 절대로 사용하지 말자**고 되어 있네요. 

그런데 아래에 있는 부분이 누락이 된 것 같은데, **구조적 프로그래밍의 목표와 규율은 공감하지만 함수가 작다면 위 규칙은 별 이익을 제공하지 못한다. 함수가 아주 클 때만 상당한 이익을 제공한다.** 이 부분을 참고하시면 될 것 같습니다.

또한 **그러므로 함수를 작게 만든다면 간혹 return, break, continue를 사용해도 괜찮다. 오히려 때로는 단일 입/출구 규칙보다 의도를 표현하기 쉬워진다.** 라고 되어 있네요. 

이에 대해 제 생각을 말씀드리자면 저희도 최근 swift 프로젝트를 하면서
 
```swift
guard let ~ 
    return;
````

부분을 많이 쓰게 되는데, 훨씬 간결하게 만들어주는 부분이 있어서 적극 도입하고 있습니다. 
하지만 규모가 큰 클래스의 경우에는 여러 early-exit 구문이 들어가면 코드를 읽기 어려워지는 점이 많아서
(저는 Android 관련 클래스들에서 많이 본 것 같네요) 그럴때는 early-exit을 고민하곤 합니다. 

클린 코드의 내용들은 기본적으로 절대라는 의미 보다는 권유의 내용들이 많아서, 저희도 그렇게 
활용을 많이 하고 있습니다.

피드백 감사합니다~

**Comment by devxoul** [comment]
답변 감사합니다.
